name: Code checks

on:
  pull_request:
    branches:
    - master
    - 'release/*'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/workflows/markdown.links.config.json'
        check-modified-files-only: 'yes'
        use-verbose-mode: 'yes'
  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - name: Yarn install
        run: yarn --immutable
      - name: Run knip
        run: yarn knip